version: '3.8'

services:
  postgres:
    image: postgres:15.10
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    image: frankmwangi8118/pos:v2
    container_name: pos-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://docker-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8721:8082" 
    depends_on:
      - postgres  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


